#!/bin/bash

# Wallpaper Backend
swww-daemon --format xrgb &

# Bar
waybar &

# Notification Daemon
swaync &

# Idle daemon to screen lock
hypridle &

# Clipboard
wl-clip-persist --clipboard regular &
wl-paste --watch cliphist store &

"$HOME"/dotfiles/.scripts/random_wallpaper.sh &

systemctl --user daemon-reload&
systemctl --user enable --now random_wallpaper.timer&


###currectly unavailable

# Automounter for removable media
# udiskie &

# Pyprland Daemon
# pypr &

# OSD Window
# swayosd-server &

# Notify about devices connecting and disconnecting
# devify &

# Polkit authentication
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Audio
# easyeffects --gapplication-service &

# Screen sharing and portals
# "$HOME"/.config/hypr/portal &
