#!/bin/bash

# Wallpaper Backend
awww-daemon --format xrgb &

# Bar
waybar &

# Notification Daemon
swaync &
# dunst &
#
ydotool &
# Idle daemon to screen lock
hypridle &

# Clipboard
wl-clip-persist --clipboard regular &
wl-paste --watch cliphist store &

systemctl --user daemon-reload &
systemctl --user enable --now random_wallpaper.timer &
systemctl --user restart random_wallpaper.service &

# Polkit authentication
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

###currectly unavailable

# Automounter for removable media
# udiskie &

# Pyprland Daemon
# pypr &

# OSD Window
# swayosd-server &

# Notify about devices connecting and disconnecting
# devify &

# Audio
# easyeffects --gapplication-service &

# Screen sharing and portals
# "$HOME"/.config/hypr/portal &
