[[shades]]
name = "vibrance"
default = true

[[shades]]
name = "blue-light-filter"
start_time = 00:00:01
end_time = 00:00:02

[[shades]]
name = "invert-colors"
start_time = 00:00:03
end_time = 00:00:04

[[shades]]
name = "grayscale"
start_time = 00:00:05
end_time = 00:00:06

[[shades]]
name = "color-filter"
start_time = 00:00:07
end_time = 00:00:08

[[shades]]
name = "dark"
start_time = 00:00:09
end_time = 00:00:10
