#!/usr/bin/env bash

wallpaperDir="$HOME/Pictures/wallpapers"
hellpaper="$HOME/App/hellpaper"

# Transition config
FPS=60
TYPE="fade"
DURATION=3
BEZIER="0.4,0.2,0.4,1.0"
awww_PARAMS="--transition-fps ${FPS} --transition-type ${TYPE} --transition-duration ${DURATION} --transition-bezier ${BEZIER}"

# Check if swaybg is running
if pidof swaybg >/dev/null; then
  pkill swaybg
fi

hellpaperCommand="hellpaper -r wallpaperDir"

# Execute command according the wallpaper manager
executeCommand() {
  if command -v awww &>/dev/null; then
    awww img "$1" ${awww_PARAMS}

  elif command -v swaybg &>/dev/null; then
    swaybg -i "$1" &

  else
    echo "Neither awww nor swaybg are installed."
    notify-send "install awww or swaybg" -t 2000
    exit 1
  fi
  rm -rf ~/.cache/awww
  ln -sf "$1" "$HOME/.current_wallpaper"
}

# If awww exists, start it
if command -v awww &>/dev/null; then
  awww query || awww init
fi

# Execution
main() {
  selected_wallpaper=$("$hellpaper" -r "$wallpaperDir")

  [[ -z "$selected_wallpaper" ]] && exit 0

  executeCommand "$selected_wallpaper"
}

main
