#!/usr/bin/env bash
# This script for selecting wallpapers (SUPER W)

# Wallpapers Path
wallpaperDir="$HOME/Pictures/wallpapers"
themesDir="$HOME/.config/rofi"
randomIcon="$HOME/.config/rofi/icons/random.png"
gifIcon="$HOME/.config/rofi/icons/gif.png"

# Transition config
FPS=60
TYPE="any"
DURATION=3
BEZIER="0.4,0.2,0.4,1.0"
SWWW_PARAMS="--transition-fps ${FPS} --transition-type ${TYPE} --transition-duration ${DURATION} --transition-bezier ${BEZIER}"

# Check if swaybg is running
if pidof swaybg >/dev/null; then
  pkill swaybg
fi

# Retrieve image files as a list
PICS=($(find "${wallpaperDir}" -type f \( -iname \*.jpg -o -iname \*.jpeg -o -iname \*.png -o -iname \*.webp -o -iname \*.gif \) | sort))

# Use date variable to increase randomness
randomNumber=$((($(date +%s) + RANDOM) + $$))
randomPicture="${PICS[$((randomNumber % ${#PICS[@]}))]}"
randomChoice="[${#PICS[@]}] Random"

# Rofi command
rofiCommand="rofi -show -dmenu -theme $HOME/.config/rofi/launchers/type-3/style-1.rasi"

# Execute command according the wallpaper manager
executeCommand() {
  if command -v swww &>/dev/null; then
    swww img "$1" ${SWWW_PARAMS} && notify-send "Wallpaper Changed" -i "$1" --app-name=Wallpaper -t 1500

  elif command -v swaybg &>/dev/null; then
    swaybg -i "$1" &

  else
    echo "Neither swww nor swaybg are installed."
    notify-send "install swaybg or swww" -t 2000
    exit 1
  fi
  rm -rf ~/.cache/swww
  ln -sf "$1" "$HOME/.current_wallpaper"
}

# Show the images
menu() {

  printf "$randomChoice\x00icon\x1f${randomIcon}\n"

  for i in "${!PICS[@]}"; do
    file="${PICS[$i]}"
    filename=$(basename "$file")
    # If not *.gif or *.webp, display
    if [[ -z $(echo "${PICS[$i]}" | grep -E '\.gif$|\.webp$') ]]; then
      printf "${filename}\x00icon\x1f${file}\n"
    else
      # Displaying .gif to indicate animated images
      printf "${filename}\x00icon\x1f${gifIcon}\n"
    fi
  done
}

# If swww exists, start it
if command -v swww &>/dev/null; then
  swww query || swww init
fi

# Execution
main() {
  choice=$(menu | ${rofiCommand})

  # No choice case
  if [[ -z $choice ]]; then
    exit 0
  fi

  # Random choice case
  if [ "$choice" = "$randomChoice" ]; then
    executeCommand "${randomPicture}"
    return 0
  fi

  # Find the selected file
  for file in "${PICS[@]}"; do
    # Getting the file
    if [[ "$(basename "$file")" = "$choice" ]]; then
      selectedFile="$file"
      break
    fi
  done

  # Check the file and execute
  if [[ -n "$selectedFile" ]]; then
    executeCommand "${selectedFile}"
    return 0
  else
    echo "Image not found."
    exit 1
  fi

}

# Check if rofi is already running
if pidof rofi >/dev/null; then
  pkill rofi
  exit 0
fi

main
